function ObtenerNombreMes(mes)
{
	var nombre="";
	if(mes==1)
		nombre="ENERO";
	else
	{
		if(mes==2)
			nombre="FEBRERO";
		else
		{
			if(mes==3)
				nombre="MARZO";
			else
			{
				if(mes==4)
					nombre="ABRIL";
				else
				{
					if(mes==5)
						nombre="MAYO";
					else
					{
						if(mes==6)
							nombre="JUNIO";
						else
						{
							if(mes==7)
								nombre="JULIO";
							else
							{
								if(mes==8)
									nombre="AGOSTO";
								else
								{
									if(mes==9)
										nombre="SEPTIEMBRE";
									else
									{
										if(mes==10)
											nombre="OCTUBRE";
										else
										{
											if(mes==11)
												nombre="NOVIEMBRE";
											else
											{
												if(mes==12)
													nombre="DICIEMBRE";
												else
													if(mes==13)
													nombre="CIERRE";
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	return nombre;
}